### ISSUE TITLE
docksal-local.env not supported

### ISSUE THREAD

**Issue by jajajaime** [nicoschi/mutagen-for-docksal#1]
First of all, thank you for this! It works great and I've been trying it on a few project and have had great success.

I ran into an issue when I tried to move the added .env configuration from `docksal.env` to `docksal-local.env`. With this, the project started behaving like mutagen was not a part of it at all.

**Comment by nicoschi** [comment]
Hi @jajajaime , `mutagen` command to work sets some variables with `fin config set VARIABLE` for getting them later. Unfortunately `fin get VARIABLE`cannot get them from docksal-local.env file. Anyway I noticed with `mutagen` command I'm setting variables not really needed, so i can rework the command. I will try to do it in the next days.

**Comment by jajajaime** [comment]
Thank you!

**Comment by nicoschi** [comment]
Hi @jajajaime , now there's a support for docksal-local.env which is the default file used on Docksal/Mutagen project creation to register needed variables. 
Can i ask you which operating system and docksal mode (vbox or native) are you using? Thanks

**Comment by jajajaime** [comment]
Awesome! I will give it a spin tomorrow.
I am running macOS Big Sur 11.1 and docksal native.

**Comment by jajajaime** [comment]
Forgot to mention that it has been running fine and working as expected with docksal-local.env.
